version: '3.8'

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: qwerty
      POSTGRES_USER: malcom
    ports:
      - "5432:5432"


  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: jdbc:postgresql://db:5432/postgres
      DATABASE_USERNAME: malcom
      DATABASE_PASSWORD: qwerty

    ports:
      - "8080:8080"
    depends_on:
      - db