spring:
  application:
    name: nutrition-control

  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 1

server:
  port: ${PORT:8080}

rsa:
  private-key: classpath:certificates/private.pem
  public-key: classpath:certificates/public.pem
