CREATE TABLE dishes (
  id BIGINT NOT NULL,
   calories_per_serving INTEGER NOT NULL,
   carbohydrates FLOAT8 NOT NULL,
   fat FLOAT8 NOT NULL,
   name VARCHAR(255),
   protein FLOAT8 NOT NULL,
   CONSTRAINT dishes_pkey PRIMARY KEY (id)
);

CREATE TABLE users (
  id BIGINT NOT NULL,
   age INTEGER NOT NULL,
   email VARCHAR(255),
   gender VARCHAR(255),
   goal VARCHAR(255),
   height FLOAT8 NOT NULL,
   name VARCHAR(255),
   weight FLOAT8 NOT NULL,
   CONSTRAINT users_pkey PRIMARY KEY (id)
);

CREATE SEQUENCE  IF NOT EXISTS dishes_seq AS bigint START WITH 1 INCREMENT BY 50 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1;

CREATE SEQUENCE  IF NOT EXISTS meals_seq AS bigint START WITH 1 INCREMENT BY 50 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1;

CREATE SEQUENCE  IF NOT EXISTS users_seq AS bigint START WITH 1 INCREMENT BY 50 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1;

CREATE TABLE meal_dish (
  meal_id BIGINT NOT NULL,
   dish_id BIGINT NOT NULL
);

CREATE TABLE meals (
  id BIGINT NOT NULL,
   created_at date,
   name VARCHAR(255),
   user_id BIGINT,
   CONSTRAINT meals_pkey PRIMARY KEY (id)
);

ALTER TABLE meals ADD CONSTRAINT fk677c66qpjr7234luomahc1ale FOREIGN KEY (user_id) REFERENCES users (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE meal_dish ADD CONSTRAINT fk9qqs2vdgj6wdv3mri1lmhu06q FOREIGN KEY (dish_id) REFERENCES dishes (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE meal_dish ADD CONSTRAINT fkmq310tlrs4hti9wb6p4vyk5pj FOREIGN KEY (meal_id) REFERENCES meals (id) ON UPDATE NO ACTION ON DELETE NO ACTION;